spring:
    datasource:
#        url: jdbc:mysql://b0f0a805937444:148c8977@eu-cdbr-west-01.cleardb.com/heroku_d2adf96c06d327c?reconnect=true
#        username: b0f0a805937444
#        password: 148c8977
        url: jdbc:mysql://localhost:3306/filmstash_db
        username: root
        password: 123456

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 35587022505-4gec75eo4ueobldcenoqpmn0qkv3ttei.apps.googleusercontent.com
              clientSecret: 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
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 86400000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,https://filmstash-backend.herokuapp.com,https://filmstash.herokuapp.com
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - https://filmstash.herokuapp.com/oauth2/redirect
      - http://localhost:3000/oauth2/redirect
      - http://localhost:8080/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect